// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testapi.Data;

namespace testapi.Migrations
{
    [DbContext(typeof(WebBanHangContext))]
    [Migration("20211218033030_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testapi.Models.Category", b =>
                {
                    b.Property<string>("idCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("nameCategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idCategory");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("testapi.Models.Product", b =>
                {
                    b.Property<string>("idProduct")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("decriptionProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dimensionsProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("discountProduct")
                        .HasColumnType("int");

                    b.Property<string>("idCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pictureProduct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("priceProduct")
                        .HasColumnType("int");

                    b.Property<int>("qualityProduct")
                        .HasColumnType("int");

                    b.Property<int>("rateProduct")
                        .HasColumnType("int");

                    b.Property<string>("weightProduct")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProduct");

                    b.ToTable("products");
                });

            modelBuilder.Entity("testapi.Models.UserProduct", b =>
                {
                    b.Property<string>("idUser")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("emailUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reviewUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.ToTable("userProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
